### PR TITLE
Update valgrind supression and define isnanf

### PR DESCRIPTION
**Pull request by ghost**
* Check if isnanf is a function or defined, if not define it as isnan
* The false positives of musl are not registered in valgrind and have to be added

### CODE REVIEW

**Comment by ganwell** [comment]
This obviously doesn't work, according to the POSIX documentation, isnan always works with double and float, there is no need for isnanf. I'll investigate that.

**Comment by ghost** [comment]
The isnanf problem could also be solved never using isnanf, since POSIX defines it in a way that works for double and float: http://www.unix.com/man-page/POSIX/3posix/isnan/

But I don't know what's the reason for using isnanf is, so I composed this patch to keep isnanf. Let me know if I should try to eliminate isnanf.

**Comment by ludocode** [comment]
Thanks 👍 `isnan()` has caused endless problems with unit tests.

I've wanted to add a bunch more functions to deal with floats in MPack, so these will probably move into the library itself at some point (as wrappers with an `mpack_` prefix.) If that's the case though I don't know how this sort of check will work since the library is meant to be included without needing any sort of configure tests. I guess we'll cross that bridge when we come to it.

**Comment by ghost** [comment]
Thanks for merging.

@ludocode if you need ideas, opinions about the isnan problems, people associated alpine-linux and musl, have a good taste for such things. You or I could start by asking in the IRC. Let me know :-)

Because:

* To learn about functions you need to probe it with build tool like scons (thats the only really reliable way)
* As in this patch, in case isnanf is a function I have to ask scons, in case isnanf is a macro I could only use macros.
* But you never know. I switch often between Windows/Linux-glibc/Linux-Musl/BSD, so many things are internally different and also change. Even the doc claims it to be POSIX. So again probing is the only way.

But you don't want probing for an amalgamation. I also write a software that is distributed as .h and I had one such case, I solved it by letting the user define a callback. Since it is a seldom used feature, the default callback is usually sufficient.

**Pull request merged**
