### PR TITLE
Initial cmake build system integration

### PR DESCRIPTION
**Pull request by xor-gate**
This is a draft to build/configure mpack with cmake.
CMake is also able to generate visual studio and Xcode projects.
Amalganition is not yet added.

Hope you like it!

### CODE REVIEW

**Comment by jerryjacobs** [comment]
After a clean build it seemed the make doc target was broken to find the source files. Have it fixed in 4d9fbcdcbd9605eedd2ad30673d0ffc83a3d8652

**Comment by ludocode** [comment]
I'm definitely interested in eventually converting the project to CMake. I think choosing SCons was probably a mistake, and CMake seems to be quite popular especially for building cross-platform projects with native tools.

However one of the reasons I chose SCons is because it makes it really easy to do variant builds. Currently when you type `scons`, the test suite isn't just built once. The whole project is built repeatedly, and run under valgrind in multiple different configurations. Currently it runs both debug/release, both 32-bit/64-bit builds, and it also does debug/release C++ builds. Like this:

https://gist.github.com/ludocode/7026af2815c18dc20377

This all happens in exactly one step, which is critical to properly test the project. I've wanted to expand quite a bit on that now that the project is more stable to focus more on testing the different mpack-config.h options. I'll soon be adding a build without stdio and a build without malloc to ensure the code will compile on the most restrictive embedded platforms. (I haven't added this yet partly because it probably doesn't work yet, and partly because I'll be making changes to the Node API first to allow it to work with node pools so as not to require malloc().)

I'd like to preserve this behaviour in a transition to CMake. This would mean CMake would need to create lots of different targets from the same codebase, and the resulting Makefile should build and run them all in one step. Ideally it would be able to set up Xcode and Visual Studio projects the same way.

I'd also like to make sure that no files in the source code depend on build system files at all. Nothing currently in the codebase outside of SConscript/SConstruct has any dependency on any build system, or requires processing of any kind. These CMake changes create a file `mpack-config.h.sample.in` for example, which doesn't really make sense. This is a sample file, meant to be dropped into a project and used as-is. Nothing in the code should require processing by the buildsystem.

In my own Android/iOS game project, mpack is included as a git submodule, and the source files (including the sample config) are just used as-is. (A symlink `mpack-config.h` points to `mpack-config.h.sample`, and the files are just dropped into Xcode.) This wouldn't be possible if the files required processing with CMake.

This patch also builds static and shared libraries which is unnecessary. I don't really want to encourage building the code into a library at all. I'm using sqlite as a model here, where you can just download their amalgamation package and drop sqlite3.c/h into your project. This should be the same idea. The build system should only be used for running unit tests.

Unfortunately I don't know nearly enough about CMake to make all of this happen. I'll be learning a lot more about it in the coming months though, so maybe we'll eventually be able to make the switch.

**Comment by jerryjacobs** [comment]
>I'm definitely interested in eventually converting the project to CMake. I think choosing SCons was >probably a mistake, and CMake seems to be quite popular especially for building cross-platform >projects with native tools.
>
>However one of the reasons I chose SCons is because it makes it really easy to do variant builds. >Currently when you type scons, the test suite isn't just built once. The whole project is built repeatedly, >and run under valgrind in multiple different configurations. Currently it runs both debug/release, both 32->bit/64-bit builds, and it also does debug/release C++ builds. Like this:

> https://gist.github.com/ludocode/7026af2815c18dc20377

I am almost 100% sure this can be archieved with cmake, it has a extensive set of features and capabilities. The idea why cmake was created is to make cross-build and cross-test easy from one build generator system.

> This all happens in exactly one step, which is critical to properly test the project. I've wanted to expand > quite a bit on that now that the project is more stable to focus more on testing the different mpack->config.h options. I'll soon be adding a build without stdio and a build without malloc to ensure the code >will compile on the most restrictive embedded platforms. (I haven't added this yet partly because it >probably doesn't work yet, and partly because I'll be making changes to the Node API first to allow it to >work with node pools so as not to require malloc().)

Totaly agree on that, in one step it is not so easy to see regressions for different configurations and is better to split them in output result but run them after each other with one command.

> I'd like to preserve this behaviour in a transition to CMake. This would mean CMake would need to
>create lots of different targets from the same codebase, and the resulting Makefile should build and run > them all in one step. Ideally it would be able to set up Xcode and Visual Studio projects the same way.

This is the way cmake work to create alot of different targets for the same codebase.

> I'd also like to make sure that no files in the source code depend on build system files at all. Nothing
> currently in the codebase outside of SConscript/SConstruct has any dependency on any build system, > or requires processing of any kind. These CMake changes create a file mpack-config.h.sample.in for
> example, which doesn't really make sense. This is a sample file, meant to be dropped into a project > and used as-is. Nothing in the code should require processing by the buildsystem.

> In my own Android/iOS game project, mpack is included as a git submodule, and the source files
> (including the sample config) are just used as-is. (A symlink mpack-config.h points to mpack-
> config.h.sample, and the files are just dropped into Xcode.) This wouldn't be possible if the files
> required processing with CMake.

> This patch also builds static and shared libraries which is unnecessary. I don't really want to encourage > building the code into a library at all. I'm using sqlite as a model here, where you can just download
> their amalgamation package and drop sqlite3.c/h into your project. This should be the same idea. The > build system should only be used for running unit tests.

I also totally agree on this.

> Unfortunately I don't know nearly enough about CMake to make all of this happen. I'll be learning a lot
> more about it in the coming months though, so maybe we'll eventually be able to make the switch.

CMake is extensively documented and gets you less gray hairs then most homecooked build scripts.

**Comment by xor-gate** [comment]
Closing this for now because of lack of interest (for now or forever, feel free to reopen).

**Comment by ludocode** [comment]
Sorry, I do still want to switch to CMake at some point to generate Xcode and Visual Studio unit testing projects. I've added AppVeyor support recently but it's only using the static Visual Studio project, so it's only full-featured debug/release builds, not the matrix of builds that the current SCons system uses. I've finally ironed out most of the issues with the SCons builds though, so this has dropped in priority. Maybe some day I'll get around to this but there's a bunch of other stuff I want to do first.

**Pull request closed without merging**
